{% set version = '1.11.3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ks
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ks_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ks/ks_{{ version }}.tar.gz
  sha256: 0d69e85fb4dc97045fdc273b36cf44b185ab60a6d7b17e1eb0c6dddf074be47c

build:
  merge_build_host: True  # [win]
  number: 1002
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed  # [win]
    - {{posix}}coreutils  # [win]
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-fnn >=1.1
    - r-kernsmooth >=2.22
    - r-matrix
    - r-kernlab
    - r-mclust
    - r-mgcv
    - r-multicool
    - r-mvtnorm >=1.0_0
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-fnn >=1.1
    - r-kernsmooth >=2.22
    - r-matrix
    - r-kernlab
    - r-mclust
    - r-mgcv
    - r-multicool
    - r-mvtnorm >=1.0_0

test:
  commands:
    - $R -e "library('ks')"           # [not win]
    - "\"%R%\" -e \"library('ks')\""  # [win]

about:
  home: http://www.mvstat.net/mvksa
  license: GPL-2 | GPL-3
  summary: 'Kernel smoothers for univariate and multivariate data, including densities, density
    derivatives, cumulative distributions, clustering, classification, density ridges,
    significant modal regions, and two-sample hypothesis tests.'
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
