{% set version = "1.14.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-ks
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ks_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ks/ks_{{ version }}.tar.gz
  sha256: f19130476cfafec26bba102b66ecbaeb80a9312c62d55eeec54d1aec75803fcb

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-matrix                   # [build_platform != target_platform]
    - r-mvtnorm                  # [build_platform != target_platform]
    - r-pracma                   # [build_platform != target_platform]
    - r-kernsmooth               # [build_platform != target_platform]
    - r-mclust                   # [build_platform != target_platform]
    - r-kernlab                  # [build_platform != target_platform]
    - r-plot3d                   # [build_platform != target_platform]
    - r-fnn                      # [build_platform != target_platform]
    - r-multicool                # [build_platform != target_platform]
    - r-mgcv                     # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-fnn >=1.1
    - r-kernsmooth >=2.22
    - r-matrix
    - r-kernlab
    - r-mclust
    - r-mgcv
    - r-multicool
    - r-mvtnorm >=1.0_0
    - r-plot3d
    - r-pracma
  run:
    - r-base
    - r-fnn >=1.1
    - r-kernsmooth >=2.22
    - r-matrix
    - r-kernlab
    - r-mclust
    - r-mgcv
    - r-multicool
    - r-mvtnorm >=1.0_0
    - r-plot3d
    - r-pracma

test:
  commands:
    - $R -e "library('ks')"           # [not win]
    - "\"%R%\" -e \"library('ks')\""  # [win]

about:
  home: http://www.mvstat.net/mvksa
  license: GPL-2.0-or-later
  summary: 'Kernel smoothers for univariate and multivariate data, including densities, density derivatives, cumulative distributions, clustering, classification, density ridges, significant modal regions, and two-sample hypothesis tests. Chacon & Duong (2018) <doi:10.1201/9780429485572>.   '
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: ks
# Version: 1.11.5
# Date: 2019-05-20
# Title: Kernel Smoothing
# Authors@R: c(person("Tarn", "Duong", role=c("aut","cre"), email="tarn.duong@gmail.com"), person("Matt", "Wand", role="ctb", email="Matt.Wand@uts.edu.au"), person("Jose", "Chacon", role="ctb", email="jechacon@unex.es"), person("Artur", "Gramacki", role="ctb", email="a.gramacki@issi.uz.zgora.pl"))
# Maintainer: Tarn Duong <tarn.duong@gmail.com>
# Depends: R (>= 2.10.0)
# Imports: FNN (>= 1.1), kernlab, KernSmooth (>= 2.22), Matrix, mclust, mgcv, multicool, mvtnorm (>= 1.0-0)
# Suggests: maps, MASS, misc3d (>= 0.4-0), OceanView, oz, rgl (>= 0.66)
# Description: Kernel smoothers for univariate and multivariate data, including densities, density derivatives, cumulative distributions, clustering, classification, density ridges, significant modal regions, and two-sample hypothesis tests. Chacon & Duong (2018) <doi:10.1201/9780429485572>.
# License: GPL-2 | GPL-3
# URL: http://www.mvstat.net/mvksa
# NeedsCompilation: yes
# Packaged: 2019-05-20 21:45:40 UTC; tduong
# Author: Tarn Duong [aut, cre], Matt Wand [ctb], Jose Chacon [ctb], Artur Gramacki [ctb]
# Repository: CRAN
# Date/Publication: 2019-05-20 22:50:04 UTC
