appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: e4jgnLqGtZA90uxrt2Nt6L99zTsBYg7w/TFXesAIXqhGDEPFchT3TjKQf8gjcsLZJ9RL5v2cHYGCsi2PNB6qU/ku/8R+hx5SwPkvQ8HGU0jIM7shdTDsiC+OlMUdBbEdWGS9GWXonNqLZxATPGjJyBbdu8BOdG2oQFI1wqE8+ej4zWV2F53yzqHvcNJ4Wyy99aLkVbXasPWfaVupC4O9Cz9dvMedB7QuxfSPeFLWQFm7DKf9v6czCkwSD1AgbooPQdNtFXKglZx9/IWqMrOccckAbvGDAqh1+wP9nuRxa1kA20uicoJCr1s+fFHGPdIBdLOiQikMd7CYp2qiM83S8df6D4gMRbxqt/RhkwvhWtt7dPELG2UI0LYeeHUw4PinYtJXX+z0eAnoX3x4vYMh+LoX7SKAqvT+PSoqrkAIIIw2qTn+PnK2LHZ+k9q37G+GXd4NFzdrjMnIlw2UaXKMvZtzYk+5GNF5IGf8NiJEuhOO5koW3J0AKNewBZ7+XRcXl+ouRPxLfktikWUb4haP3jLRBaWWo06OjZQ9MhnlI2wetqYMoP3oWMk/SOILaoW8uPASbhHm0lBbGQ5SDYiVir8Cr9TvNS+nlujfE58SbjZ9xR+SHmSk/eukXWyEzdyb8IIeUlcwBCM211+XLl63ayVfYYTDeptlBSXYOUKRP68=}
